name: clockimate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_dotenv: ^5.1.0
  timezone: ^0.9.2
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - .env